export function parseModelJson(response, fallback) {
  if (!response) return fallback;

  let cleaned = response.trim();

  if (cleaned.startsWith('```')) {
    const firstNewline = cleaned.indexOf('\n');
    if (firstNewline !== -1) {
      cleaned = cleaned.slice(firstNewline + 1);
    }
    if (cleaned.endsWith('```')) {
      cleaned = cleaned.slice(0, -3);
    }
    cleaned = cleaned.trim();
  }

  cleaned = cleaned.replace(/^json\s*/i, '').trim();

  try {
    return JSON.parse(cleaned);
  } catch {
    try {
      return JSON.parse(cleaned.replace(/,\s*}/g, '}').replace(/,\s*]/g, ']'));
    } catch {
      return fallback;
    }
  }
}

export function parseStage3Response(response, item) {
  const fallbackClaim = item.claim;
  const fallbackSources = item.snippets.slice(0, 3).map(s => ({
    title: s.title,
    url: s.url,
    relevant: false
  }));

  const parsed = parseModelJson(response, null);
  if (!parsed) {
    return {
      claim: fallbackClaim,
      rating: 'Smelly',
      explanation: 'Could not parse the verification result. The small model produced malformed output — try a bigger model tier for more reliable answers.',
      sources: fallbackSources
    };
  }

  const rating = ['Fresh', 'Bullshit', 'Smelly'].includes(parsed.rating) ? parsed.rating : 'Smelly';
  const hasExplanation = typeof parsed.explanation === 'string' && parsed.explanation.trim().length > 0;
  const sources = Array.isArray(parsed.sources) && parsed.sources.length > 0 ? parsed.sources : fallbackSources;

  if (!hasExplanation) {
    const topTitles = item.snippets.slice(0, 2).map(s => s.title).filter(Boolean).join('; ');
    return {
      claim: parsed.claim || fallbackClaim,
      rating: 'Smelly',
      explanation: topTitles
        ? 'The model gave a verdict but no explanation, so we downgraded it to "Smelly" out of caution. Relevant sources found: ' + topTitles + '. Check them yourself below.'
        : 'The model gave a verdict but no explanation, so we downgraded it to "Smelly" out of caution. Try a bigger model tier for more reliable reasoning.',
      sources
    };
  }

  return {
    claim: parsed.claim || fallbackClaim,
    rating,
    explanation: parsed.explanation.trim(),
    sources
  };
}

export function calculateOverallRating(verdicts) {
  if (verdicts.length === 0) return 0;

  let total = 0;
  for (const v of verdicts) {
    if (v.rating === 'Fresh') total += 0;
    else if (v.rating === 'Smelly') total += 50;
    else if (v.rating === 'Bullshit') total += 100;
    else total += 50;
  }

  return Math.round(total / verdicts.length);
}

export function summarizeVerdicts(verdicts) {
  const fresh = verdicts.filter(v => v.rating === 'Fresh').length;
  const smelly = verdicts.filter(v => v.rating === 'Smelly').length;
  const bullshit = verdicts.filter(v => v.rating === 'Bullshit').length;
  const total = verdicts.length;

  return {
    fresh,
    smelly,
    bullshit,
    total,
    bullshitPct: total > 0 ? Math.round(100 * bullshit / total) : 0,
    uncheckedPct: total > 0 ? Math.round(100 * smelly / total) : 0
  };
}

export function reportToMarkdown(verdicts, summary) {
  let lines = '# Bullshit Report\n';
  lines += '**' + summary.total + ' claims checked — ' + summary.fresh + ' confirmed, ' + summary.smelly + ' unverified, ' + summary.bullshit + ' contradicted**\n';
  lines += '\n## 🔴 Bullshit\n';

  const bullshit = verdicts.filter(v => v.rating === 'Bullshit');
  if (bullshit.length === 0) {
    lines += '_None_';
  } else {
    for (const v of bullshit) {
      lines += '- **' + v.claim + '** — ' + v.explanation + '\n';
      for (const s of (v.sources || [])) {
        lines += '  - ' + s.title + ': ' + s.url + '\n';
      }
    }
  }

  lines += '\n## 🟡 Smelly\n';

  const smelly = verdicts.filter(v => v.rating === 'Smelly');
  if (smelly.length === 0) {
    lines += '_None_';
  } else {
    for (const v of smelly) {
      lines += '- **' + v.claim + '** — ' + v.explanation + '\n';
      for (const s of (v.sources || [])) {
        lines += '  - ' + s.title + ': ' + s.url + '\n';
      }
    }
  }

  lines += '\n## 🟢 Fresh\n';

  const fresh = verdicts.filter(v => v.rating === 'Fresh');
  if (fresh.length === 0) {
    lines += '_None_';
  } else {
    for (const v of fresh) {
      lines += '- **' + v.claim + '** — ' + v.explanation + '\n';
      for (const s of (v.sources || [])) {
        lines += '  - ' + s.title + ': ' + s.url + '\n';
      }
    }
  }

  lines += '\n_Generated by LLM Bullshit Detector_\n';

  return lines;
}